import React, {useState, useEffect} from 'react'
import { nacelleClient } from 'services'

import ContentSections from '../components/Sections/ContentSections'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ pages }) {
  const sections = pages[0].fields.sections
  console.log(sections, "sections", pages)
  // const homePage = pages.find((page) => page.handle === 'homepage')
  return (
    <div>
      <Head>
        <title>Healthy Baby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <ContentSections sections={sections} />
      </main>
    </div>
  )
}

export async function getStaticProps({ previewData }) {
  try {
    const pages = await nacelleClient.content({
      handles: ['homepage']
    })

    return {
      props: { pages }
    }
  } catch {
    // fake hero image section until Sanity is hooked up
    const page = {
      fields: {
          sections: [
            {
              fields: {
                handle: "",
                title: "",
                subtitle: "",
                ctaText: "",
                ctaUrl: "",
                textColor: "",
              }
            }
          ]
      }
    }

    return {
      props: {
        page
      }
    }
  }
}